config/routes.rb
Rails.application.routes.draw do
  get "signup" => 'users#new'
  resources :users
  # note that these are singular - this will remove the id portion of the routes bc each user will only have one session resource.  Rails calls this a singular resource
  # be careful: the routes use the singular version of session, but the controller will use the plural form: sessions_controller.rb
  resource :session
  root "events#index"
  # took generated resources for registrations and nested them in a block for events
  # this will allow us to navigate to (for example) URLs with /events/:event_id/registrations
  resources :events do
    resources :registrations
  end
  # get "events" => "events#index"
  # get "events/new" => "events#new"
  # get "events/:id" => "events#show", as: "event"
  # get "events/:id/edit" => "events#edit", as: "edit_event"
  # patch "events/:id" => "events#update"

end

app/models/event.rb
class Event < ApplicationRecord
  # this tells the event model to expect an event_id column in the table wrapped by the registration model
  # dependent: :destroy tells active record to destroy all the child objects (registrations) in the database if the event is destroyed
  has_many :registrations, dependent: :destroy

  validates :name, :location, presence: true
  validates :description, length: {minimum: 25}
  validates :price, numericality: { greater_than_or_equal_to: 0}
  validates :capacity, numericality: {only_integer: true, grater_than: 0}
  validates :image_file_name, allow_blank: true, format: {
    with: /\w+\.(gif|jpg|png)\z/i,
    message: "must reference a GIF, JPG, or PNG image"
  }

  def free?
    # price == 0
    price.blank? || price.zero?
  end

# this is a class level method that acts on the class and not an instance of the class so we use "self" in the method name
  def self.upcoming
    where("starts_at >= ?", Time.now).order("starts_at")
  end

  def spots_left
    # not sure why I have access to registrations here
    capacity - registrations.size
  end

  def sold_out?
    # event.spots_left == 0
    spots_left.zero?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    # @events = Event.all
    @events = Event.upcoming
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
     if @event.update(event_params)
      # # don't want to go to an update view template so we redirect
      # redirect_to events_path(@event)
      # # rails has a shortcut for this too
      # flash[:notice] = "Event successfully updated!"
      # redirect_to @event
      # # OR...
      redirect_to @event, notice: "Event successfully updated"
    else
      render :edit
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event
    else
      # render the form again with the previously entered submissions
      render :new
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_url
  end

private

  def event_params
    params.require(:event).permit(:name, :description, :location, :price, :starts_at, :image_file_name, :capacity)
  end

end

app/helpers/events_helper.rb
module EventsHelper
  def format_price(event)
    if event.free?
      content_tag(:strong, "Free")
    else
      number_to_currency(event.price)
    end
  end

  def image_for(event)
    if event.image_file_name.blank?
      image_tag 'placeholder.png'
    else
      image_tag event.image_file_name
    end
  end

  def register_link(event)
    # if event.spots_left == 0
    if event.sold_out?
      content_tag(:strong, "Sold Out!")
    else
      link_to "Register", new_event_registration_path(event)
    end
  end
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <!-- using shared error code for the event and registration forms that has a local varialbe called object. here we are setting the value of that object variable to @event so any errors on the event form will go to the error handling code %> -->
  <%= render 'shared/errors', object: @event %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, autofocus: true %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description, cols: 40, rows: 7 %>
  </p>
  <p>
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </p>
  <p>
    <%= f.label :starts_at %><br>
    <%= f.datetime_select :starts_at %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </p>
  <p>
    <%= f.label :image_file_name %><br>
    <%= f.text_field :image_file_name, size: 30, placeholder: "GIF, JPG, or PNG file name" %>
  </p>
  <p>
    <%= f.label :capacity %><br>
    <%= f.number_field :capacity %>
  </p>
  <p>
    <%= f.submit %> |
    <%= link_to "Cancel", events_path %>
  </p>
<% end %>

app/views/events/edit.html.erb
<h1>Edit <%= @event.name %></h1>

<%= render 'form' %>

app/views/events/index.html.erb
<h1><%= pluralize @events.size, 'Event' %></h1>

<% @events.each do |event| %>
    <article class="event">
      <header>
        <!-- <%#= image_tag event.image_file_name %> -->
        <!-- replacing with custom helper -->
        <%= image_for(event) %>
        <h2><%= link_to event.name, event_path(event) %></h2>
        <h3><%#= pluralize(event.capacity, 'spot')%></h3>
        <h3><%= pluralize(event.spots_left, 'spot')%> available</h3> 
      </header>
      <p>
        <%= truncate(event.description, length: 35, separator: ' ') %>
      </p>
      <table>
        <tr>
          <th>When:</th>
          <td><%= event.starts_at %></td>
        </tr>
        <tr>
          <th>Where:</th>
          <td><%= event.location %></td>
        </tr>
        <tr>
          <th>Price:</th>
          <td><%= format_price event %></td>
        </tr>
      </table>
    </article>
  <% end %>

app/views/events/new.html.erb
<h1>Add New Event</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<article class="">
  <header>
    <%= image_for(@event) %>
    <h2><%= @event.name %></h2>
  </header>
  <p>
    <%= @event.description %>
  </p>
  <table>
    <tr>
      <th>When:</th>
      <td><%= @event.starts_at %></td>
    </tr>
    <tr>
      <th>Where:</th>
      <td><%= @event.location %></td>
    </tr>
    <tr>
      <th>Price:</th>
      <td><%= format_price(@event) %></td>
    </tr>
    <tr>
      <th>Capacity:</th>
      <td><%= pluralize(@event.capacity, 'spot') %></td>
    </tr>
  </table>
  <%= link_to "Who's Registered?", event_registrations_path(@event) %>
</article>

<!-- <footer> -->
<!-- custom helper method to display 'register' or 'sold-out' -->
  <%= register_link(@event) %>
  <p>
    (<%= pluralize(@event.spots_left, 'spot') %> available)
  </p>
  <nav>
    <%= link_to "Edit", edit_event_path(@event) %> |
    <%= link_to "Delete", event_path(@event), method: :delete, data: {confirm: "Are you sure?"} %>
  </nav>
<!-- </footer> -->