config/routes.rb
Rails.application.routes.draw do
  get "signup" => 'users#new'
  resources :users
  # note that these are singular - this will remove the id portion of the routes bc each user will only have one session resource.  Rails calls this a singular resource
  # be careful: the routes use the singular version of session, but the controller will use the plural form: sessions_controller.rb
  resource :session
  root "events#index"
  # took generated resources for registrations and nested them in a block for events
  # this will allow us to navigate to (for example) URLs with /events/:event_id/registrations
  resources :events do
    resources :registrations
  end
  # get "events" => "events#index"
  # get "events/new" => "events#new"
  # get "events/:id" => "events#show", as: "event"
  # get "events/:id/edit" => "events#edit", as: "edit_event"
  # patch "events/:id" => "events#update"

end

app/views/layouts/_aside.html.erb
<aside>
  <nav>
    <ul>
      <li>
        <%= link_to "All Events", events_path %>
      </li>
      <li>
        <%= link_to "Add New Event", new_event_path %>
      </li>
    </ul>
  </nav>

  </aside>

app/views/layouts/_footer.html.erb
<footer>
  <p>
    A code along project from Pragmatic Studios
  </p>
</footer>

app/views/layouts/_header.html.erb
<header class="page-header">
  <h1><%= link_to "Coding Calendar", root_path %></h1>
  <nav>
    <p>


      <% if current_user %>
        <%= link_to current_user.name, current_user %>
        <%= link_to "Sign Out", session_path, method: :delete %>
      <% else %>
        <%# link_to "Sign Up", new_user_path  %>
        <%# created named route so now we can use: %>
        <%= link_to "Sign Up", signup_path %>
        <%= link_to "Sign In", new_session_path %>
      <% end %>
    </p>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <% if flash[:notice] %>
      <p>
        <%= flash[:notice] %>
      </p>
    <% end %>
    
    <%= render 'layouts/aside' %>

    <%= yield %>

    <%= render 'layouts/footer'%>
  </body>
</html>